reorder_imports = true
edition = "2021"
imports_granularity = "Crate"
use_small_heuristics = "Max"
comment_width = 100
wrap_comments = true
binop_separator = "Back"
trailing_comma = "Vertical"
trailing_semicolon = false
use_field_init_shorthand = true
chain_width = 40
ignore = [
    "substreams/ethereum-uniswap-v2/src/abi",
    "substreams/ethereum-uniswap-v3/src/abi",
]
