name: Test workflow

on:
  push:
    branches:
      - test/test-branch

jobs:
  check-release:
    uses: propeller-heads/ci-cd-templates/.github/workflows/release-v2.yaml@test/test-branch
    with:
      args: --dry-run --no-ci
    permissions:
      contents: write # to be able to publish a GitHub release
      issues: write # to be able to comment on released issues
      pull-requests: write # to be able to comment on released pull requests
      id-token: write # to enable use of OIDC for npm provenance
    secrets:
      app_id: ${{ secrets.APP_ID }}
      app_private_key: ${{ secrets.APP_PRIVATE_KEY }}
